# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 76eb52d4240d632afe52fa740ff8095071c1bf86a91de0c9827bec1cec1d4873a4f3476c7d0b15ac5ba5cce057bd86bf549e8806fcaf6dd8a226057dc8304682
  vkontakte_app_id: 6642709
  vkontakte_app_secret: dtTtg9HKr90newlLdvy6

  github_app_id: Iv1.f23af8c45da6daf4
  github_app_secret: 764446ef95a45f732de4ec63548b13aded2d8fee

test:
  secret_key_base: 19ef8b522ddb894fa6cd036dea8d9ad4af641f3f83b8a2706776b81907c23accfac192fbf10c5653f85917b77dcc5a5465fbe75f8b5984cf83a10fcf920ef51c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  vkontakte_app_id: <%= ENV["VKONTAKTE_APP_ID"] %>
  vkontakte_app_secret: <%= ENV["VKONTAKTE_APP_SECRET"] %>

  github_app_id: <%= ENV["GITHUB_APP_ID"] %>
  github_app_secret: <%= ENV["GITHUB_APP_SECRET"] %>
